
version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27010:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - .:/app
    restart: unless-stopped
